services:
  web-app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    image: t-fors-web-app
    container_name: t-fors-web-app
    restart: unless-stopped
    # volumes:
    #   - .:/app
    ports:
      - 8501:8501

  api:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    image: t-fors-api
    container_name: t-fors-api
    restart: unless-stopped
    # volumes:
    #   - .:/app
    ports:
      - 8000:8000